package com.gcu.inventoryapp.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * Entity class that represents a product record in the inventory system.
 * Each Product object is mapped to a database table through JPA.
 */
@Entity
public class Product {
    /**
     * Unique database identifier for each product record.
     * The value is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long productId;

    private String productName;
    private String category;
    private int quantity;
    private double price;
    private String supplier;
    private String description;

    /**
     * Default constructor required by JPA.
     */
    public Product() {
    }

    /**
     * Creates a Product object with inventory details.
     *
     * @param productName name of the product
     * @param category    category the product belongs to
     * @param quantity    number of items available
     * @param price       product price
     * @param supplier    supplier or vendor name
     * @param description description of the product
     */
    public Product(String productName, String category, int quantity, double price, String supplier, String description) {
        this.productName = productName;
        this.category = category;
        this.quantity = quantity;
        this.price = price;
        this.supplier = supplier;
        this.description = description;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public String getSupplier() {
        return supplier;
    }

    public void setSupplier(String supplier) {
        this.supplier = supplier;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}